# Generated by Django 3.0.3 on 2020-03-31 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobiesId', models.IntegerField()),
                ('hobiesName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillId', models.IntegerField()),
                ('skillName', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
                ('dob', models.DateTimeField()),
                ('gender', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('github', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=5000)),
                ('hobbies', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='customer.Hobbies')),
                ('skill', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='customer.Skill')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
